[build]
  command = "npm run build"
  publish = "build"
	functions = "functions"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[edge_functions]]
  path = "/*"
  function = "render"
