name: "Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: "Eslint"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Eslint"
        run: "npm run eslint"

  prettier:
    name: "Prettier"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Prettier"
        run: "npm run prettier"

  build:
    name: "Build"
    needs: ["eslint", "prettier"]
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Build"
        run: "npm run build --if-present"
