name: "Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: "Eslint"
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_STRAPI_URI: "http://localhost"
      PUBLIC_GRAPHQL_URI: "http://localhost/graphql"
      PUBLIC_MAIL_URI: "http://localhost/api/send/mail"
      PUBLIC_MAIL_ACCESS_TOKEN: "XXX"
      PUBLIC_PLATFORM: "dev"
      PUBLIC_RE_CAPTCHA_KEY: "XXX"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Eslint"
        run: "npm run eslint"

  stylelint:
    name: "Stylelint"
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_STRAPI_URI: "http://localhost"
      PUBLIC_GRAPHQL_URI: "http://localhost/graphql"
      PUBLIC_MAIL_URI: "http://localhost/api/send/mail"
      PUBLIC_MAIL_ACCESS_TOKEN: "XXX"
      PUBLIC_PLATFORM: "dev"
      PUBLIC_RE_CAPTCHA_KEY: "XXX"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Stylelint"
        run: "npm run stylelint"

  prettier:
    name: "Prettier"
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_STRAPI_URI: "http://localhost"
      PUBLIC_GRAPHQL_URI: "http://localhost/graphql"
      PUBLIC_MAIL_URI: "http://localhost/api/send/mail"
      PUBLIC_MAIL_ACCESS_TOKEN: "XXX"
      PUBLIC_PLATFORM: "dev"
      PUBLIC_RE_CAPTCHA_KEY: "XXX"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Prettier"
        run: "npm run prettier"

  check:
    name: "Svelte Check"
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_STRAPI_URI: "http://localhost"
      PUBLIC_GRAPHQL_URI: "http://localhost/graphql"
      PUBLIC_MAIL_URI: "http://localhost/api/send/mail"
      PUBLIC_MAIL_ACCESS_TOKEN: "XXX"
      PUBLIC_PLATFORM: "dev"
      PUBLIC_RE_CAPTCHA_KEY: "XXX"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Svelte Check"
        run: "npm run check"

  build:
    name: "Build"
    needs: ["eslint", "prettier", "stylelint", "check"]
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - name: "Use Node.js 16"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Build"
        run: "npm run build --if-present"
