name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Install
        uses: ./.github/workflows/checkout-install.yml

      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Install
        uses: ./.github/workflows/checkout-install.yml

      - name: Build
        run: npm run build --if-present
